---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instance
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "practice" # Add your key pair
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
      network:
        assign_public_ip: true
      image_id: "{{ item.ami }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { name: 'manage-node-1', ami: 'ami-00bb6a80f01f03502' }
      - { name: 'manage-node-2', ami: 'ami-00bb6a80f01f03502' }
      - { name: 'manage-node-3', ami: 'ami-0ddfba243cbee3768' }
